// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9srAVBLif6kBwpfoFHOmpMVWI6jxseqU',
    appId: '1:141898750687:web:b0447dc887f88d4512a76a',
    messagingSenderId: '141898750687',
    projectId: 'compraventavehiculos-2d210',
    authDomain: 'compraventavehiculos-2d210.firebaseapp.com',
    storageBucket: 'compraventavehiculos-2d210.firebasestorage.app',
    measurementId: 'G-YD3QH7QTM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAvmWN5EulwWKEafqNaKkoyrM-fKxu2s',
    appId: '1:141898750687:android:cbbac6cf51d06a9a12a76a',
    messagingSenderId: '141898750687',
    projectId: 'compraventavehiculos-2d210',
    storageBucket: 'compraventavehiculos-2d210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6CKDPHkAHefJdgrlEVs2vybPNXGFyxs',
    appId: '1:141898750687:ios:c3ed2b516221def312a76a',
    messagingSenderId: '141898750687',
    projectId: 'compraventavehiculos-2d210',
    storageBucket: 'compraventavehiculos-2d210.firebasestorage.app',
    iosBundleId: 'com.example.pantallas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6CKDPHkAHefJdgrlEVs2vybPNXGFyxs',
    appId: '1:141898750687:ios:c3ed2b516221def312a76a',
    messagingSenderId: '141898750687',
    projectId: 'compraventavehiculos-2d210',
    storageBucket: 'compraventavehiculos-2d210.firebasestorage.app',
    iosBundleId: 'com.example.pantallas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9srAVBLif6kBwpfoFHOmpMVWI6jxseqU',
    appId: '1:141898750687:web:8a7d91f0da9b62ef12a76a',
    messagingSenderId: '141898750687',
    projectId: 'compraventavehiculos-2d210',
    authDomain: 'compraventavehiculos-2d210.firebaseapp.com',
    storageBucket: 'compraventavehiculos-2d210.firebasestorage.app',
    measurementId: 'G-E4HMB6CJPY',
  );
}
